[package]
name = "starlit-eyes"
version = "0.1.0"
edition = "2021"
authors = ["James Zow <jameszow@wansen.email>"]
license = "MIT"
rust-version = "1.71.1"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tensorflow = "0.20.0"